version: '3'
services:
  redis:
    image: redislabs/redismod:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '5540:5540'
    volumes:
      - ./redisinsight:/db
