version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-management
    hostname: rabbitmq
    ports:
      - "5673:5672"
      - "15672:15672"
      - "5552:5552"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      # MacOS
      # - ~/docker-data/rabbitmq:/var/lib/rabbitmq
      # Windows
      - D:/DockerMount/rabbitmq:/var/lib/rabbitmq
      - D:/DockerMount/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - D:/DockerMount/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5
      
# volumes:
#   rabbitmq_data: 